### PR TITLE
Increasing documentation : how to install

### PR DESCRIPTION
**Pull request by gautiermichelin**
Increasing documentation : how to install

### CODE REVIEW

**Comment by gautiermichelin** [comment]
Hi Nuvole,

I had some difficulties to enable directly your Drupal module, so I took the liberty for this PR to readme.MD

Path to JS and CSS are taken from simplemde.libraries.yml

I had to enable Libraries to activate the module, so I added it. If it's not required, please get back to me so I update my file.

Gautier

**Comment by AminSarafraz** [comment]
Hi, I followed the instruction but still couldn't install. Are you sure the library path is still this one?
`libraries/simplemde-markdown-editor/dist/simplemde.min.js`

**Comment by geek-merlin** [comment]
ThiIt looks like tis has significantly changed since the PR was created. Surely this needs documentation as it is not trivial. Something like:

* Copy the vcs repository definition from the module's composer.json to your root composer.json
* Only then do `composer require drupal/simplemde`

**Comment by gautiermichelin** [comment]
This a 3 years old thread, not merged, so I'm closing it.
If you're interested @AminSarafraz @geek-merlin don't hesitate to try with another PR. Seems to me the developers are not really looking at those, no comment in 3 years, that's enough for me.

**Pull request closed without merging**
